name: EASECHAOS BUILD
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: EaseCHAOS
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2.4-alpine3.19
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: 
          REDIS_HOST: redis
        options: >-
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        id: dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
